{{- range .Values.volumes -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "name" $ }}-volume-{{ .name }}
spec:
  accessModes:
    {{- (.accessModes | default (list "ReadWriteOnce")) | toYaml | nindent 4 }}
  volumeMode: {{ .volumeMode | default "Filesystem" }}
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: {{ .storageClass | default "default" }}
---

{{- end }}
