{{- range .Values.volumes -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "name" $ }}-volume-{{ .name }}
spec:
  accessModes:
    {{- (.accessModes | default (list "ReadWriteMany")) | toYaml | nindent 4 }}
  {{- if .volumeMode }}
  volumeMode: {{ .volumeMode }}
  {{- end }}
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: {{ .storageClass | default "default" }}
---

{{- end }}
